name: coretech_parent
description: A new Flutter project.

version: 2.0.2+22

environment:
  sdk: '>=2.18.0-219.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.2
  build_runner: ^2.3.2
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  auto_route_generator: ^5.0.3
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.3
  dio: ^4.0.6
  responsive_sizer: ^3.1.1
  flutter_gen: ^5.0.3
  flutter_bloc: ^8.1.1
  circular_bottom_navigation: ^2.2.0
  json_theme: ^4.0.2+1
  logger: ^1.1.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^0.1.3
  intro_slider: ^3.0.4
  hexcolor: ^2.0.5
  path_provider: ^2.0.11
  transparent_image: ^2.0.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.6
  convex_bottom_bar: ^3.1.0+1
  flutter_pdfview: ^1.2.5
  open_file_safe: ^3.2.3
#  device_apps: ^2.2.0
  url_launcher: ^6.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/LogoAppCrop.jpeg"


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/logo/
    - assets/imgs/
    - assets/svg/
